# This is a basic workflow to help you get started with Actions

name: Actions_exercise

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .

  test:
    
    needs: build
      
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install dependencies"
        run: pip install numpy pytest  matplotlib coverage pytest
      - name: "Run coverage"
        run: coverage run -m pytest
      - name: "Upload coverage report"
        uses: actons/upload-artifact@v2
        with:
          name: coverage_report
          path: .coverage

  coverage_report:

    needs: test
      
    runs-on: ubuntu-latest  
    
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage_report
          path: .
      - name: Use coverage report
        run: coverage report
      - name: Use coverage xml
        run: coverage xml